### ISSUE TITLE
Rock Pi 3A

### ISSUE THREAD

**Issue by arturkmat** [citruz/haos-rockpi#39]
### Describe the issue you are experiencing

I have a rock pi 3a. Maybe you plan to deploy this board?

### What operating system image do you use?

rockpi-4a

### What version of Home Assistant Operating System is installed?

1

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

Rock Pi 3A

### Steps to reproduce the issue

1.
2.nothing
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

**Comment by citruz** [comment]
Hey, no sorry this is currently not planned.
