### ISSUE TITLE
Google Assistant SDK

### ISSUE THREAD

**Issue by chunk1970** [citruz/haos-rockpi#8]
### Describe the issue you are experiencing

Hi,

Currently enjoying using HA on my rock pi 4b and it's been solid with no issues.

One thing that has cropped up where I cannot seem to install the Google assistant sdk as it reports unsupported os or processor.

Any ideas or help is much appreciated.

### What operating system image do you use?

rockpi-4b-plus

### What version of Home Assistant Operating System is installed?

Latest version 

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the Host logs that might be useful for us?

```txt
No
```

**Comment by citruz** [comment]
The Addon is not supported on arm64/aarch64 which is the architecture of the RockPi processor. Sorry, there is nothing that we can change about that. You could try asking the HA folks for the reason why it is not supported and whether someone might care to port it to arm64.

https://github.com/home-assistant/addons/blob/master/google_assistant/README.md
