### ISSUE TITLE
Radxa Zero support

### ISSUE THREAD

**Issue by jjdenhertog** [citruz/haos-rockpi#9]
### Describe the issue you are experiencing

Great work on this! I've tested this on a Radxa zero but that is unfortunately not working. Is this something you can support?

### Steps to reproduce the issue

1. Download rock pi 4B+ image
2. Add to SSD
3. Insert into radxa zero
4. Device is not booting

**Comment by citruz** [comment]
Hi, sorry this is unfortunately not possible. I don’t have the board and I would seriously doubt that HA runs on it because of the limited hardware. At least a RPi 3 or equivalent is recommended.
